### PR TITLE
Add logging and only delete on first insert!

### PR DESCRIPTION
**Pull request by quiiver**
* Added the dockerflow logging standard to the logging configuration.
* Added a bunch of logging statements in various parts of the job. Especially around the sanitized inserts.
* New function parameter for controlling destination table deletion.
* Only delete the destination partition on the first call to the insert function (when page_count == 0)

### CODE REVIEW

**Comment by chelseatroy** [comment]
Pulling down and running!

**Comment by chelseatroy** [comment]
Job appears to be working! Nice work. It's tough for me to evaluate the veracity of the outputs of the changed job because the staging tables don't face the production issue we are having where some of the sanitized queries are missing. I think we can merge this and keep an eye on the numbers in the runs the few days afterward to see what we get.

**Review by chelseatroy — APPROVED** [review]
See comments!

**Comment by quiiver** [comment]
Verified the log outputs match the expectations:

```sh
(venv) ➜  cat /tmp/job_log.json | jq '.Fields.row_count' | grep -v null | awk 'BEGIN{n=0} {n+=$1} END{print n}'
1402968
(venv) ➜  cat /tmp/job_log.json | jq '.Fields.page_size' | grep -v null | awk 'BEGIN{n=0} {n+=$1} END{print n}'
1717603
(venv) ➜  cat /tmp/job_log.json | jq '.Fields.total_rows' | grep -v null
1717603

```

**Pull request merged**
